//! Config loading. Looks at `~/.config/construct/config.toml`, merging built-in
//! adapter defaults underneath.

use agentd_protocol::paths::Paths;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::{BTreeMap, HashMap};

/// The full config template written to `config.toml.template` on every daemon
/// start. All configurable parameters are listed with their default values and
/// explanatory comments. The daemon always overwrites this file so it stays
/// current when construct is upgraded.
///
/// Also surfaced by `construct daemon default-config` for scripted inspection.
pub const CONFIG_TOML_TEMPLATE: &str = r#"# construct configuration template
# Generated by the daemon on startup — always reflects the current version.
# This file is overwritten on every daemon start; edit config.toml instead.
#
# Active config:  ~/.config/construct/config.toml  (or $CONSTRUCT_CONFIG_DIR/config.toml)
# This template:  ~/.config/construct/config.toml.template
#
# All built-in adapters (shell, claude, codex, antigravity, smith) are
# registered automatically — you do not need to declare them unless you want
# to change a field.

# ── Adapters ─────────────────────────────────────────────────────────────────
#
# Each [adapters.<name>] entry registers or overrides a harness. The daemon
# locates the binary next to itself or via PATH; use `binary` to pin an
# absolute path.
#
# Built-in adapters registered automatically (no config required):
#   shell       — generic shell command runner
#   claude      — Claude Code (wraps the `claude` CLI)
#   codex       — OpenAI Codex (wraps the `codex` CLI)
#   antigravity — Google Antigravity (wraps the `agy` CLI)
#   smith       — native multi-provider agent (OpenAI / Anthropic / Gemini / Ollama / Grok)

# [adapters.shell]
# binary      = "construct"                 # default: resolved from PATH / next to daemon
# args        = ["__adapter", "shell"]      # default: built-in dispatch args
# description = "Generic shell command runner"  # shown in harness picker

# [adapters.claude]
# binary      = "construct"
# args        = ["__adapter", "claude"]
# description = "Claude Code (wraps the `claude` CLI)"

# [adapters.codex]
# binary      = "construct"
# args        = ["__adapter", "codex"]
# description = "OpenAI Codex (wraps the `codex` CLI)"

# [adapters.antigravity]
# binary      = "construct"
# args        = ["__adapter", "antigravity"]
# description = "Google Antigravity (wraps the `agy` CLI)"

# [adapters.smith]
# binary      = "construct"
# args        = ["__adapter", "smith"]
# description = "Built-in multi-provider agent (OpenAI / Anthropic / Gemini / Ollama / Grok)"

# Per-harness environment variables ──────────────────────────────────────────
#
# `env` is a table of key = "value" pairs merged into every session spawned
# under this harness. Lets operators set per-harness defaults (e.g. a default
# model) from config.toml without exporting vars in the shell that starts the
# daemon. Per-session `construct new --env KEY=VAL` takes precedence.
#
# Smith model selection (pick one, or omit to use whatever the CLI/env sets):
#
# [adapters.smith.env]
# CONSTRUCT_SMITH_MODEL = "anthropic:claude-sonnet-4-6"   # direct API via ANTHROPIC_API_KEY
# # CONSTRUCT_SMITH_MODEL = "claude-oauth:claude-sonnet-4-6"  # via Claude subscription
# # CONSTRUCT_SMITH_MODEL = "openai:gpt-4o"                   # direct API via OPENAI_API_KEY
# # CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-4o"              # via OpenAI subscription
# # CONSTRUCT_SMITH_MODEL = "grok-oauth:grok-2-latest"        # via Grok subscription
# # CONSTRUCT_SMITH_MODEL = "gemini:gemini-2.5-pro"           # via GEMINI_API_KEY
# # CONSTRUCT_SMITH_MODEL = "ollama:llama3.1"                 # local Ollama server
# # CONSTRUCT_SMITH_MODEL = "@deepseek"                       # named profile (see [smith.models.*])

# Override the CLI binary a built-in adapter launches. CONSTRUCT_*_CMD is split
# shell-style (quotes/backslashes only; no shell expansion) and prepended before
# the adapter's generated arguments. Wins over the binary-only CONSTRUCT_*_BIN.
#
# [adapters.codex.env]
# CONSTRUCT_CODEX_CMD = "exec codex"        # also: CONSTRUCT_CLAUDE_CMD, CONSTRUCT_SHELL_CMD, CONSTRUCT_ANTIGRAVITY_CMD

# Community / custom adapters — any binary that speaks the AHP protocol:
#
# [adapters.aider]
# binary      = "construct-adapter-aider"
# description = "Aider (community adapter)"

# ── Defaults ─────────────────────────────────────────────────────────────────

[defaults]
# When true, every new session whose cwd is a git repo gets its own isolated
# git worktree. Override per session with `construct new ... --worktree`.
# Default: false
worktree = false

# ── Orchestrator (minibuffer) ─────────────────────────────────────────────────
#
# The orchestrator is a persistent smith session rendered as the minibuffer
# at the bottom of the TUI. It receives fleet-wide events and can dispatch
# commands to other sessions.

[orchestrator]
# Which harness backs the orchestrator session. Set to "" or use enabled =
# false to disable the orchestrator entirely — clients fall back to the
# static command palette.
# Default: "smith"
harness = "smith"

# Hard kill switch. Set to false to disable the orchestrator even when
# `harness` is configured.
# Default: true
enabled = true

# ── Smith named model profiles ────────────────────────────────────────────────
#
# Named endpoint profiles for the smith harness. Reference at runtime with
# `/model @<name>` (or `--model @<name>`). Lets multiple endpoints of the
# same wire protocol coexist — unlike the single OPENAI_BASE_URL env var.
#
# `provider` is the wire protocol: openai | anthropic | gemini | grok | ollama
#
# OAuth-backed providers (claude-oauth / codex-oauth / grok-oauth) are not
# configurable here — they have no base-URL/key surface.

# OpenAI-compatible example (DeepSeek):
# [smith.models.deepseek]
# provider    = "openai"
# base_url    = "https://api.deepseek.com/v1"
# api_key_env = "DEEPSEEK_API_KEY"   # name of the env var holding the key (preferred)
# # api_key   = "sk-..."             # inline key (discouraged; use api_key_env)
# model       = "deepseek-chat"      # default model; overridable with @deepseek:<model>

# OpenAI-compatible example (Groq):
# [smith.models.groq]
# provider    = "openai"
# base_url    = "https://api.groq.com/openai/v1"
# api_key_env = "GROQ_API_KEY"
# model       = "llama-3.3-70b-versatile"

# Local Ollama:
# [smith.models.local]
# provider = "ollama"
# base_url = "http://localhost:11434"   # default Ollama port; omit to use the default
# model    = "llama3.1"                 # no api_key needed for Ollama

# Anthropic direct API:
# [smith.models.claude]
# provider    = "anthropic"
# api_key_env = "ANTHROPIC_API_KEY"
# model       = "claude-sonnet-4-6"

# Gemini direct API:
# [smith.models.gemini]
# provider    = "gemini"
# api_key_env = "GEMINI_API_KEY"
# model       = "gemini-2.5-pro"

# ── Environment variable reference ────────────────────────────────────────────
#
# These env vars are read by the daemon or adapters at runtime. They are NOT
# part of config.toml — set them in the shell that launches the daemon (or in
# a systemd unit / launchd plist / wrapper script).
#
# Path overrides (XDG-style):
#   CONSTRUCT_CONFIG_DIR   — config directory  (default: ~/.config/construct)
#   CONSTRUCT_STATE_DIR    — state directory   (default: ~/.local/state/construct)
#   CONSTRUCT_DATA_DIR     — data directory    (default: ~/.local/share/construct)
#   CONSTRUCT_RUNTIME_DIR  — runtime directory (default: same as state dir)
#   XDG_CONFIG_HOME / XDG_STATE_HOME / XDG_DATA_HOME / XDG_RUNTIME_DIR also apply.
#
# Daemon:
#   CONSTRUCT_WEBUI_PORT      — local web UI port (default: 5746)
#   CONSTRUCT_REMOTE_WS_PORT  — auto-start remote WS listener on this port at boot
#
# Smith harness (can also be set per-adapter via [adapters.smith.env]):
#   CONSTRUCT_SMITH_MODEL         — default model (provider:name, @profile, or oauth prefix)
#   CONSTRUCT_SMITH_AUTOMODE      — set to "1" to enable autonomous mode by default
#   CONSTRUCT_SMITH_MAX_STEPS     — max tool-call steps per turn
#   CONSTRUCT_SMITH_MAX_TURN_SECS — max seconds per turn
#   CONSTRUCT_SMITH_HOOKS_JSON    — inline JSON hooks config
#   CONSTRUCT_SMITH_HOOKS_CONFIG  — path to a hooks config file
#   CONSTRUCT_SHELL_BIN           — shell binary used by smith hooks
#
# Operator / orchestrator:
#   CONSTRUCT_OPERATOR_LOOP_DISABLED      — set to "1" to disable the ambient loop
#   CONSTRUCT_OPERATOR_MONITOR_MODEL      — model used for the ambient monitor
#   CONSTRUCT_OPERATOR_AMBIENT_LOOP_SECS  — ambient loop interval in seconds
#   CONSTRUCT_OPERATOR_ACTIVE_WINDOW_SECS — active-window duration in seconds
#   CONSTRUCT_LOOP_MIN_SECS               — minimum loop interval
#   CONSTRUCT_LOOP_MAX_SECS               — maximum loop interval
#
# Adapter CLI overrides (set in [adapters.<name>.env] or the outer shell):
#   CONSTRUCT_CLAUDE_CMD      — command prefix for the claude adapter
#   CONSTRUCT_CODEX_CMD       — command prefix for the codex adapter
#   CONSTRUCT_ANTIGRAVITY_CMD — command prefix for the antigravity adapter
#   CONSTRUCT_SHELL_CMD       — command prefix for the shell adapter
#   CONSTRUCT_CLAUDE_BIN      — binary path fallback for the claude adapter
#   CONSTRUCT_CODEX_BIN       — binary path fallback for the codex adapter
"#;

/// Kept for backwards-compat: `construct daemon default-config` and any
/// external code that imports this name still works.
pub const DEFAULT_CONFIG_TOML: &str = CONFIG_TOML_TEMPLATE;

/// Write (or overwrite) `config.toml.template` in the config directory.
/// Called on every daemon start so the template stays current after upgrades.
/// Failure is non-fatal — a warning is logged and the daemon continues.
pub fn write_template(paths: &Paths) {
    let path = paths.config_template_file();
    if let Err(e) = std::fs::write(&path, CONFIG_TOML_TEMPLATE) {
        tracing::warn!(path = %path.display(), error = %e, "could not write config.toml.template");
    } else {
        tracing::debug!(path = %path.display(), "wrote config.toml.template");
    }
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub adapters: BTreeMap<String, AdapterConfig>,
    #[serde(default)]
    pub defaults: Defaults,
    #[serde(default)]
    pub orchestrator: OrchestratorConfig,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OrchestratorConfig {
    /// Which harness backs the daemon-created orchestrator session.
    /// `None` (TOML: `harness = ""` or `enabled = false`) disables
    /// the orchestrator entirely — clients then fall back to the
    /// static command palette. Default: `"smith"`.
    #[serde(default)]
    pub harness: Option<String>,
    /// Hard kill switch; set to `false` to disable the orchestrator
    /// even when `harness` is configured. Default: `true`.
    #[serde(default = "default_orchestrator_enabled")]
    pub enabled: bool,
}

fn default_orchestrator_enabled() -> bool {
    true
}

impl Default for OrchestratorConfig {
    fn default() -> Self {
        Self {
            harness: Some("smith".to_string()),
            enabled: true,
        }
    }
}

impl OrchestratorConfig {
    /// The effective harness name when the orchestrator is enabled.
    pub fn effective_harness(&self) -> Option<&str> {
        if !self.enabled {
            return None;
        }
        self.harness.as_deref().filter(|s| !s.is_empty())
    }
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct AdapterConfig {
    #[serde(default)]
    pub binary: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub args: Vec<String>,
    /// Extra environment variables to inject when spawning this
    /// adapter. Lets operators set per-harness defaults — e.g. a
    /// default model — from `config.toml` without touching the
    /// shell where the daemon launches. Merged INTO the per-session
    /// `env_with_meta` (see `daemon/src/session.rs`); existing
    /// per-session env takes precedence so an explicit
    /// `construct new --env KEY=VAL` still overrides.
    ///
    /// Example: pin every new smith session to use an explicit
    /// subscription-backed OAuth path instead of the heuristic fallback:
    ///
    /// ```toml
    /// [adapters.smith]
    /// env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5" }
    /// # or: env = { CONSTRUCT_SMITH_MODEL = "claude-oauth:sonnet" }
    /// # or: env = { CONSTRUCT_SMITH_MODEL = "grok-oauth:grok-2-latest" }
    /// ```
    #[serde(default)]
    pub env: HashMap<String, String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Defaults {
    #[serde(default)]
    pub worktree: Option<bool>,
}

pub struct BuiltinAdapter {
    pub name: &'static str,
    pub binary: &'static str,
    pub args: &'static [&'static str],
    pub description: &'static str,
}

pub const BUILTIN_ADAPTERS: &[BuiltinAdapter] = &[
    BuiltinAdapter {
        name: "shell",
        binary: "construct",
        args: &["__adapter", "shell"],
        description: "Generic shell command runner",
    },
    BuiltinAdapter {
        name: "claude",
        binary: "construct",
        args: &["__adapter", "claude"],
        description: "Claude Code (wraps the `claude` CLI)",
    },
    BuiltinAdapter {
        name: "codex",
        binary: "construct",
        args: &["__adapter", "codex"],
        description: "OpenAI Codex (wraps the `codex` CLI)",
    },
    BuiltinAdapter {
        name: "antigravity",
        binary: "construct",
        args: &["__adapter", "antigravity"],
        description: "Google Antigravity (wraps the `agy` CLI)",
    },
    BuiltinAdapter {
        name: "grok",
        binary: "construct",
        args: &["__adapter", "grok"],
        description: "Grok CLI (wraps the `grok` CLI)",
    },
    BuiltinAdapter {
        name: "smith",
        binary: "construct",
        args: &["__adapter", "smith"],
        description: "Built-in multi-provider agent (OpenAI / Anthropic / Gemini / Ollama / Grok)",
    },
];

impl Config {
    pub fn load_or_default(paths: &Paths) -> Result<Self> {
        let path = paths.config_file();
        let mut cfg = if path.exists() {
            let s = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            toml::from_str::<Config>(&s).with_context(|| format!("parse {}", path.display()))?
        } else {
            Self::default()
        };
        // Layer in built-ins so users don't have to declare them.
        // Important: we layer at the FIELD level, not the entry level
        // — a user who declared `[adapters.smith] env = {...}` (only
        // to set per-harness env defaults) still needs the builtin
        // `binary` + `description` to fill in. Without this,
        // declaring an `[adapters.<name>]` block to set ONE field
        // would silently drop the builtin's binary path and the
        // daemon would fail with "adapter binary not found" on
        // session create.
        for b in BUILTIN_ADAPTERS {
            let entry = cfg.adapters.entry(b.name.to_string()).or_default();
            if entry.binary.is_none() {
                entry.binary = Some(b.binary.to_string());
            }
            if entry.args.is_empty() {
                entry.args = b.args.iter().map(|s| s.to_string()).collect();
            }
            if entry.description.is_none() {
                entry.description = Some(b.description.to_string());
            }
        }
        Ok(cfg)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `[adapters.<name>].env` parses out of TOML and lands on the
    /// resolved AdapterConfig.
    #[test]
    fn adapter_env_table_parses() {
        let toml = r#"
            [adapters.smith]
            binary = "construct-adapter-smith"
            env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5", DEBUG = "1" }
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert_eq!(
            smith.env.get("CONSTRUCT_SMITH_MODEL").map(String::as_str),
            Some("codex-oauth:gpt-5.5"),
        );
        assert_eq!(smith.env.get("DEBUG").map(String::as_str), Some("1"));
    }

    /// Omitting `env` is fine — it defaults to empty rather than
    /// failing the parse.
    #[test]
    fn adapter_env_defaults_to_empty() {
        let toml = r#"
            [adapters.smith]
            binary = "construct-adapter-smith"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert!(smith.env.is_empty());
    }

    /// REGRESSION: declaring `[adapters.smith] env = {…}` (to set
    /// per-harness env defaults — the motivating use case for that
    /// field) must NOT drop the built-in `binary` / `description`
    /// values that the daemon needs to actually spawn the adapter.
    ///
    /// Before this fix, the BUILTIN_ADAPTERS layer used
    /// `or_insert_with`, which only fired when the entry was
    /// missing entirely. A user-supplied entry that lacked `binary`
    /// got NO `binary` field, the daemon fell back to looking up a
    /// binary named bare `smith` (not `construct-adapter-smith`),
    /// and session create failed with "adapter binary not found".
    #[test]
    fn user_partial_adapter_config_keeps_builtin_binary() {
        let toml = r#"
            [adapters.smith]
            env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5" }
        "#;
        let mut cfg: Config = toml::from_str(toml).expect("parse");
        // Mimic Config::load's builtin-layering step (the actual
        // load() walks the filesystem, which we'd rather not in
        // tests).
        for b in BUILTIN_ADAPTERS {
            let entry = cfg.adapters.entry(b.name.to_string()).or_default();
            if entry.binary.is_none() {
                entry.binary = Some(b.binary.to_string());
            }
            if entry.args.is_empty() {
                entry.args = b.args.iter().map(|s| s.to_string()).collect();
            }
            if entry.description.is_none() {
                entry.description = Some(b.description.to_string());
            }
        }
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert_eq!(
            smith.binary.as_deref(),
            Some("construct"),
            "user-supplied [adapters.smith] with only `env` set must still pick up the built-in binary path",
        );
        // And the user's env stays in place.
        assert_eq!(
            smith.env.get("CONSTRUCT_SMITH_MODEL").map(String::as_str),
            Some("codex-oauth:gpt-5.5"),
        );
    }
}
