//! Config loading. Looks at `~/.config/construct/config.toml`, merging built-in
//! adapter defaults underneath.

use construct_protocol::paths::Paths;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

/// Env override for the program-templates directory. Wins over the
/// `[program].templates_dir` config option; both fall back to the default
/// `data_dir/program/templates`.
pub const PROGRAM_TEMPLATES_DIR_ENV: &str = "CONSTRUCT_PROGRAM_TEMPLATES_DIR";

/// The full config template written to `config.toml.template` on every daemon
/// start. All configurable parameters are listed with their default values and
/// explanatory comments. The daemon always overwrites this file so it stays
/// current when construct is upgraded.
///
/// Also surfaced by `construct daemon default-config` for scripted inspection.
pub const CONFIG_TOML_TEMPLATE: &str = r#"# construct configuration template
# Generated by the daemon on startup — always reflects the current version.
# This file is overwritten on every daemon start; edit config.toml instead.
#
# Active config:  ~/.config/construct/config.toml  (or $CONSTRUCT_CONFIG_DIR/config.toml)
# This template:  ~/.config/construct/config.toml.template
#
# All built-in adapters (shell, claude, codex, antigravity, smith) are
# registered automatically — you do not need to declare them unless you want
# to change a field.

# ── Adapters ─────────────────────────────────────────────────────────────────
#
# Each [adapters.<name>] entry registers or overrides a harness. The daemon
# locates the binary next to itself or via PATH; use `binary` to pin an
# absolute path.
#
# Built-in adapters registered automatically (no config required):
#   shell       — generic shell command runner
#   claude      — Claude Code (wraps the `claude` CLI)
#   codex       — OpenAI Codex (wraps the `codex` CLI)
#   antigravity — Google Antigravity (wraps the `agy` CLI)
#   smith       — native multi-provider agent (OpenAI / Anthropic / Gemini / Ollama / Grok)

# [adapters.shell]
# binary      = "construct"                 # default: resolved from PATH / next to daemon
# args        = ["__adapter", "shell"]      # default: built-in dispatch args
# description = "Generic shell command runner"  # shown in harness picker

# [adapters.claude]
# binary      = "construct"
# args        = ["__adapter", "claude"]
# description = "Claude Code (wraps the `claude` CLI)"

# [adapters.codex]
# binary      = "construct"
# args        = ["__adapter", "codex"]
# description = "OpenAI Codex (wraps the `codex` CLI)"

# [adapters.agy]
# binary      = "construct"
# args        = ["__adapter", "agy"]
# description = "Google Antigravity (wraps the `agy` CLI)"

# [adapters.smith]
# binary      = "construct"
# args        = ["__adapter", "smith"]
# description = "Built-in multi-provider agent (OpenAI / Anthropic / Gemini / Ollama / Grok)"

# Per-harness environment variables ──────────────────────────────────────────
#
# `env` is a table of key = "value" pairs merged into every session spawned
# under this harness. Lets operators set per-harness defaults (e.g. a default
# model) from config.toml without exporting vars in the shell that starts the
# daemon. Per-session `construct new --env KEY=VAL` takes precedence.
#
# Smith model selection (pick one, or omit if ANTHROPIC_API_KEY / OPENAI_API_KEY /
# GEMINI_API_KEY (or GOOGLE_API_KEY) is set in the daemon's environment — smith
# auto-detects those three, in that order. Without a pin AND without one of those
# three set, smith fails to start with an error rather than silently falling back
# to a local Ollama that may not be running. OAuth subscriptions and Ollama always
# need an explicit pin here (or --model / CONSTRUCT_SMITH_MODEL per-session) since
# there's no way to auto-detect them safely. The construct TUI's `/configure`
# dialog (smith-auth tab) writes this same key for you after showing live status
# for every method below.
#
# [adapters.smith.env]
# CONSTRUCT_SMITH_MODEL = "anthropic:claude-sonnet-4-6"   # direct API via ANTHROPIC_API_KEY
# # CONSTRUCT_SMITH_MODEL = "claude-oauth:claude-sonnet-4-6"  # via Claude subscription
# # CONSTRUCT_SMITH_MODEL = "openai:gpt-5.5"                  # direct API via OPENAI_API_KEY
# # CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5"             # via OpenAI subscription
# # CONSTRUCT_SMITH_MODEL = "grok-oauth:grok-2-latest"        # via Grok subscription
# # CONSTRUCT_SMITH_MODEL = "gemini:gemini-2.5-pro"           # via GEMINI_API_KEY
# # CONSTRUCT_SMITH_MODEL = "ollama:llama3.1"                 # local Ollama server
# # CONSTRUCT_SMITH_MODEL = "@deepseek"                       # named profile (see [smith.models.*])

# Override the CLI binary a built-in adapter launches. CONSTRUCT_*_CMD is split
# shell-style (quotes/backslashes only; no shell expansion) and prepended before
# the adapter's generated arguments. Wins over the binary-only CONSTRUCT_*_BIN.
#
# [adapters.codex.env]
# CONSTRUCT_CODEX_CMD = "exec codex"        # also: CONSTRUCT_CLAUDE_CMD, CONSTRUCT_SHELL_CMD, CONSTRUCT_ANTIGRAVITY_CMD

# Usage-probe command ────────────────────────────────────────────────────────
#
# `usage_probe` is the interactive slash command the daemon sends to a
# short-lived ephemeral session to capture this harness's own usage/status
# panel (spec 0086), cached for 5 minutes and surfaced as a hover tooltip.
# The raw rendered output is captured and redisplayed verbatim — never
# parsed into token counts or other structured fields.
#
# Unset (the default): the harness's built-in usage command runs —
#   claude -> "/usage", codex -> "/status", agy -> "/usage", grok -> "/usage show".
# Empty string: disables the probe entirely for this harness.
# Any other string: sent verbatim instead of the built-in default.
#
# [adapters.claude]
# usage_probe = "/usage"     # same as the built-in default; shown for discoverability
#
# [adapters.codex]
# usage_probe = ""           # disable the usage probe for codex

# Community / custom adapters — any binary that speaks the AHP protocol:
#
# [adapters.aider]
# binary      = "construct-adapter-aider"
# description = "Aider (community adapter)"

# ── Defaults ─────────────────────────────────────────────────────────────────

[defaults]
# When true, every new session whose cwd is a git repo gets its own isolated
# git worktree. Override per session with `construct new ... --worktree`.
# Default: false
worktree = false

# ── Orchestrator (minibuffer) ─────────────────────────────────────────────────
#
# The orchestrator is a persistent smith session rendered as the minibuffer
# at the bottom of the TUI. It receives fleet-wide events and can dispatch
# commands to other sessions.

[orchestrator]
# Which harness backs the orchestrator session. Set to "" or use enabled =
# false to disable the orchestrator entirely — clients fall back to the
# static command palette.
# Default: "smith"
harness = "smith"

# Hard kill switch. Set to false to disable the orchestrator even when
# `harness` is configured.
# Default: true
enabled = true

# ── Program ──────────────────────────────────────────────────────────────────
#
# The program is the shared Markdown space each session can run. Built-in
# templates (Blank, Tasks, Investigation, Goal) are always offered; drop your own
# `<name>.md` files in the templates directory to add custom templates. A custom
# template is just a Markdown file — its filename is its name and its contents are
# the program. Custom templates reload on every program open — no daemon restart
# needed.

# [program]
# Directory custom program templates are read from.
# Default: <data_dir>/program/templates  (e.g. ~/.local/share/construct/program/templates)
# The CONSTRUCT_PROGRAM_TEMPLATES_DIR env var overrides this.
# templates_dir = "/path/to/my/program-templates"

# ── Smith named model profiles ────────────────────────────────────────────────
#
# Named endpoint profiles for the smith harness. Reference at runtime with
# `/model @<name>` (or `--model @<name>`). Lets multiple endpoints of the
# same wire protocol coexist — unlike the single OPENAI_BASE_URL env var.
#
# `provider` is the wire protocol: openai | anthropic | gemini | grok | ollama
#
# OAuth-backed providers (claude-oauth / codex-oauth / grok-oauth) are not
# configurable here — they have no base-URL/key surface.

# OpenAI-compatible example (DeepSeek):
# [smith.models.deepseek]
# provider    = "openai"
# base_url    = "https://api.deepseek.com/v1"
# api_key_env = "DEEPSEEK_API_KEY"   # name of the env var holding the key (preferred)
# # api_key   = "sk-..."             # inline key (discouraged; use api_key_env)
# model       = "deepseek-chat"      # default model; overridable with @deepseek:<model>

# OpenAI-compatible example (Groq):
# [smith.models.groq]
# provider    = "openai"
# base_url    = "https://api.groq.com/openai/v1"
# api_key_env = "GROQ_API_KEY"
# model       = "llama-3.3-70b-versatile"

# Local Ollama:
# [smith.models.local]
# provider = "ollama"
# base_url = "http://localhost:11434"   # default Ollama port; omit to use the default
# model    = "llama3.1"                 # no api_key needed for Ollama

# Anthropic direct API:
# [smith.models.claude]
# provider    = "anthropic"
# api_key_env = "ANTHROPIC_API_KEY"
# model       = "claude-sonnet-4-6"

# Gemini direct API:
# [smith.models.gemini]
# provider    = "gemini"
# api_key_env = "GEMINI_API_KEY"
# model       = "gemini-2.5-pro"

# ── Environment variable reference ────────────────────────────────────────────
#
# These env vars are read by the daemon or adapters at runtime. They are NOT
# part of config.toml — set them in the shell that launches the daemon (or in
# a systemd unit / launchd plist / wrapper script).
#
# Path overrides (XDG-style):
#   CONSTRUCT_HOME         — base directory for config, state, data, and run path overrides
#   CONSTRUCT_CONFIG_DIR   — config directory  (default: $CONSTRUCT_HOME/config or ~/.config/construct)
#   CONSTRUCT_STATE_DIR    — state directory   (default: $CONSTRUCT_HOME/state or ~/.local/state/construct)
#   CONSTRUCT_DATA_DIR     — data directory    (default: $CONSTRUCT_HOME/data or ~/.local/share/construct)
#   CONSTRUCT_RUNTIME_DIR  — runtime directory (default: $CONSTRUCT_HOME/run or same as state dir)
#   XDG_CONFIG_HOME / XDG_STATE_HOME / XDG_DATA_HOME / XDG_RUNTIME_DIR also apply.
#
# Daemon:
#   CONSTRUCT_WEBUI_PORT      — local web UI port (default: 5746)
#   CONSTRUCT_REMOTE_WS_PORT  — auto-start remote WS listener on this port at boot
#   CONSTRUCT_PROGRAM_TEMPLATES_DIR — program templates dir (overrides [program].templates_dir)
#
# Smith harness (can also be set per-adapter via [adapters.smith.env]):
#   CONSTRUCT_SMITH_MODEL         — default model (provider:name, @profile, or oauth prefix)
#   CONSTRUCT_SMITH_AUTOMODE      — set to "1" to enable autonomous mode by default
#   CONSTRUCT_SMITH_MAX_STEPS     — max tool-call steps per turn
#   CONSTRUCT_SMITH_MAX_TURN_SECS — max seconds per turn
#   CONSTRUCT_SMITH_HOOKS_JSON    — inline JSON hooks config
#   CONSTRUCT_SMITH_HOOKS_CONFIG  — path to a hooks config file
#   CONSTRUCT_SHELL_BIN           — shell binary used by smith hooks
#
# Operator / orchestrator:
#   CONSTRUCT_OPERATOR_LOOP_DISABLED      — set to "1" to disable the ambient loop
#   CONSTRUCT_OPERATOR_MONITOR_MODEL      — model used for the ambient monitor
#   CONSTRUCT_OPERATOR_AMBIENT_LOOP_SECS  — ambient loop interval in seconds
#   CONSTRUCT_OPERATOR_ACTIVE_WINDOW_SECS — active-window duration in seconds
#   CONSTRUCT_LOOP_MIN_SECS               — minimum loop interval
#   CONSTRUCT_LOOP_MAX_SECS               — maximum loop interval
#
# Adapter CLI overrides (set in [adapters.<name>.env] or the outer shell):
#   CONSTRUCT_CLAUDE_CMD      — command prefix for the claude adapter
#   CONSTRUCT_CODEX_CMD       — command prefix for the codex adapter
#   CONSTRUCT_ANTIGRAVITY_CMD — command prefix for the antigravity adapter
#   CONSTRUCT_SHELL_CMD       — command prefix for the shell adapter
#   CONSTRUCT_CLAUDE_BIN      — binary path fallback for the claude adapter
#   CONSTRUCT_CODEX_BIN       — binary path fallback for the codex adapter
"#;

/// Kept for backwards-compat: `construct daemon default-config` and any
/// external code that imports this name still works.
pub const DEFAULT_CONFIG_TOML: &str = CONFIG_TOML_TEMPLATE;

/// Write (or overwrite) `config.toml.template` in the config directory.
/// Called on every daemon start so the template stays current after upgrades.
/// Failure is non-fatal — a warning is logged and the daemon continues.
pub fn write_template(paths: &Paths) {
    let path = paths.config_template_file();
    if let Err(e) = std::fs::write(&path, CONFIG_TOML_TEMPLATE) {
        tracing::warn!(path = %path.display(), error = %e, "could not write config.toml.template");
    } else {
        tracing::debug!(path = %path.display(), "wrote config.toml.template");
    }
}

/// Set (or clear) `[adapters.smith.env] CONSTRUCT_SMITH_MODEL` in the live
/// `config.toml`, preserving every other table/comment via a format-
/// preserving edit (`toml_edit`) — the `/configure` dialog's smith-auth tab
/// (spec 0069) is the only caller, and users may have hand-written
/// unrelated config alongside it. `model_spec: None` clears the pin,
/// restoring smith's default auto-detect ladder.
pub fn set_smith_model_pin(paths: &Paths, model_spec: Option<&str>) -> Result<()> {
    let path = paths.config_file();
    let existing = if path.exists() {
        std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?
    } else {
        String::new()
    };
    let mut doc = existing
        .parse::<toml_edit::DocumentMut>()
        .with_context(|| format!("parse {}", path.display()))?;
    let adapters = ensure_subtable(&mut doc, "adapters")?;
    let smith = ensure_subtable(adapters, "smith")?;
    let env = ensure_subtable(smith, "env")?;
    match model_spec {
        Some(spec) => {
            env.insert("CONSTRUCT_SMITH_MODEL", toml_edit::value(spec));
        }
        None => {
            env.remove("CONSTRUCT_SMITH_MODEL");
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    std::fs::write(&path, doc.to_string()).with_context(|| format!("write {}", path.display()))
}

/// Get-or-insert a subtable of `table`, marking a freshly-created one
/// implicit so it doesn't print its own `[key]` header when it exists only
/// to hold a deeper table (matches how `toml_edit` renders supertables of a
/// dotted path like `[adapters.smith.env]`).
fn ensure_subtable<'a>(
    table: &'a mut toml_edit::Table,
    key: &str,
) -> Result<&'a mut toml_edit::Table> {
    let entry = table.entry(key).or_insert_with(|| {
        let mut t = toml_edit::Table::new();
        t.set_implicit(true);
        toml_edit::Item::Table(t)
    });
    entry
        .as_table_mut()
        .ok_or_else(|| anyhow::anyhow!("`{key}` in config.toml is not a table"))
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub adapters: BTreeMap<String, AdapterConfig>,
    #[serde(default)]
    pub defaults: Defaults,
    #[serde(default)]
    pub orchestrator: OrchestratorConfig,
    #[serde(default)]
    pub program: ProgramConfig,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct ProgramConfig {
    /// Directory program templates are read from. When unset, the daemon uses
    /// `<data_dir>/program/templates`. The `CONSTRUCT_PROGRAM_TEMPLATES_DIR`
    /// env var overrides this.
    #[serde(default)]
    pub templates_dir: Option<String>,
}

impl Config {
    /// Resolve the program-templates directory override. Precedence:
    /// `CONSTRUCT_PROGRAM_TEMPLATES_DIR` env > `[program].templates_dir` config >
    /// default (`None`, leaving the daemon's `data_dir/program/templates`).
    pub fn program_templates_dir_override(&self) -> Option<PathBuf> {
        let env = std::env::var(PROGRAM_TEMPLATES_DIR_ENV).ok();
        resolve_program_templates_dir(self, env.as_deref())
    }
}

/// Pure resolver for the program-templates directory override, separated from
/// the live env read so precedence (env > config > default) is unit-testable.
pub fn resolve_program_templates_dir(cfg: &Config, env_override: Option<&str>) -> Option<PathBuf> {
    if let Some(v) = env_override.map(str::trim).filter(|s| !s.is_empty()) {
        return Some(PathBuf::from(v));
    }
    cfg.program
        .templates_dir
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
}

#[derive(Debug, Clone, Deserialize)]
pub struct OrchestratorConfig {
    /// Which harness backs the daemon-created orchestrator session.
    /// `None` (TOML: `harness = ""` or `enabled = false`) disables
    /// the orchestrator entirely — clients then fall back to the
    /// static command palette. Default: `"smith"`.
    #[serde(default)]
    pub harness: Option<String>,
    /// Hard kill switch; set to `false` to disable the orchestrator
    /// even when `harness` is configured. Default: `true`.
    #[serde(default = "default_orchestrator_enabled")]
    pub enabled: bool,
}

fn default_orchestrator_enabled() -> bool {
    true
}

impl Default for OrchestratorConfig {
    fn default() -> Self {
        Self {
            harness: Some("smith".to_string()),
            enabled: true,
        }
    }
}

impl OrchestratorConfig {
    /// The effective harness name when the orchestrator is enabled.
    pub fn effective_harness(&self) -> Option<&str> {
        if !self.enabled {
            return None;
        }
        self.harness.as_deref().filter(|s| !s.is_empty())
    }
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct AdapterConfig {
    #[serde(default)]
    pub binary: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub args: Vec<String>,
    /// Extra environment variables to inject when spawning this
    /// adapter. Lets operators set per-harness defaults — e.g. a
    /// default model — from `config.toml` without touching the
    /// shell where the daemon launches. Merged INTO the per-session
    /// `env_with_meta` (see `daemon/src/session.rs`); existing
    /// per-session env takes precedence so an explicit
    /// `construct new --env KEY=VAL` still overrides.
    ///
    /// Example: pin every new smith session to use an explicit
    /// subscription-backed OAuth path instead of the heuristic fallback:
    ///
    /// ```toml
    /// [adapters.smith]
    /// env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5" }
    /// # or: env = { CONSTRUCT_SMITH_MODEL = "claude-oauth:sonnet" }
    /// # or: env = { CONSTRUCT_SMITH_MODEL = "grok-oauth:grok-2-latest" }
    /// ```
    #[serde(default)]
    pub env: HashMap<String, String>,
    /// The interactive slash command a usage-probe session sends to capture
    /// this harness's own usage/status panel (spec 0086). TOML has no
    /// `null` literal, so "absent" and "explicitly unset" collapse to the
    /// same state; the three-way split is: absent (`None` here) → the
    /// built-in default command for this harness; explicit `""` → probe
    /// disabled; any other string → sent verbatim instead of the default.
    /// Resolve via [`Config::effective_usage_probe`], never this field
    /// directly.
    #[serde(default)]
    pub usage_probe: Option<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Defaults {
    #[serde(default)]
    pub worktree: Option<bool>,
}

pub struct BuiltinAdapter {
    pub name: &'static str,
    pub binary: &'static str,
    pub args: &'static [&'static str],
    pub description: &'static str,
}

pub const BUILTIN_ADAPTERS: &[BuiltinAdapter] = &[
    BuiltinAdapter {
        name: "shell",
        binary: "construct",
        args: &["__adapter", "shell"],
        description: "Generic shell command runner",
    },
    BuiltinAdapter {
        name: "claude",
        binary: "construct",
        args: &["__adapter", "claude"],
        description: "Claude Code (wraps the `claude` CLI)",
    },
    BuiltinAdapter {
        name: "codex",
        binary: "construct",
        args: &["__adapter", "codex"],
        description: "OpenAI Codex (wraps the `codex` CLI)",
    },
    BuiltinAdapter {
        name: "agy",
        binary: "construct",
        args: &["__adapter", "agy"],
        description: "Google Antigravity (wraps the `agy` CLI)",
    },
    BuiltinAdapter {
        name: "grok",
        binary: "construct",
        args: &["__adapter", "grok"],
        description: "Grok CLI (wraps the `grok` CLI)",
    },
    BuiltinAdapter {
        name: "smith",
        binary: "construct",
        args: &["__adapter", "smith"],
        description: "Built-in multi-provider agent (OpenAI / Anthropic / Gemini / Ollama / Grok)",
    },
];

/// Built-in usage-probe command for each harness that has an interactive
/// usage/status slash command (spec 0086). Harnesses not listed here
/// (`shell`, `smith`) have no probe unless an operator sets `usage_probe`
/// explicitly in `config.toml`.
const DEFAULT_USAGE_PROBE: &[(&str, &str)] = &[
    ("claude", "/usage"),
    ("codex", "/status"),
    ("agy", "/usage"),
    // Bare "/usage" opens grok's usage menu without picking an action;
    // "show" is the subcommand that actually renders the limits panel
    // (confirmed live: an invalid `/usage <x>` argument error message
    // points at exactly "/usage show" or "/usage manage").
    ("grok", "/usage show"),
];

fn default_usage_probe(harness: &str) -> Option<&'static str> {
    DEFAULT_USAGE_PROBE
        .iter()
        .find(|(name, _)| *name == harness)
        .map(|(_, cmd)| *cmd)
}

impl Config {
    /// The command a usage-probe session should send for `harness`
    /// (spec 0086), or `None` when probing is disabled for it. Mirrors the
    /// empty-string-means-unset convention `OrchestratorConfig::effective_harness`
    /// uses: an explicit `usage_probe = ""` disables the probe, an absent
    /// field falls back to the harness's built-in default command (see
    /// [`DEFAULT_USAGE_PROBE`]), and any other string is sent verbatim.
    pub fn effective_usage_probe(&self, harness: &str) -> Option<&str> {
        match self.adapters.get(harness).and_then(|a| a.usage_probe.as_deref()) {
            Some(s) if !s.is_empty() => Some(s),
            Some(_) => None, // explicit "" -> disabled
            None => default_usage_probe(harness),
        }
    }

    pub fn load_or_default(paths: &Paths) -> Result<Self> {
        let path = paths.config_file();
        let mut cfg = if path.exists() {
            let s = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            toml::from_str::<Config>(&s).with_context(|| format!("parse {}", path.display()))?
        } else {
            Self::default()
        };
        // Layer in built-ins so users don't have to declare them.
        // Important: we layer at the FIELD level, not the entry level
        // — a user who declared `[adapters.smith] env = {...}` (only
        // to set per-harness env defaults) still needs the builtin
        // `binary` + `description` to fill in. Without this,
        // declaring an `[adapters.<name>]` block to set ONE field
        // would silently drop the builtin's binary path and the
        // daemon would fail with "adapter binary not found" on
        // session create.
        for b in BUILTIN_ADAPTERS {
            let entry = cfg.adapters.entry(b.name.to_string()).or_default();
            if entry.binary.is_none() {
                entry.binary = Some(b.binary.to_string());
            }
            if entry.args.is_empty() {
                entry.args = b.args.iter().map(|s| s.to_string()).collect();
            }
            if entry.description.is_none() {
                entry.description = Some(b.description.to_string());
            }
        }
        Ok(cfg)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_paths(tmp: &std::path::Path) -> Paths {
        Paths {
            config_dir: tmp.to_path_buf(),
            state_dir: tmp.to_path_buf(),
            data_dir: tmp.to_path_buf(),
            runtime_dir: tmp.to_path_buf(),
        }
    }

    /// The `/configure` dialog's smith-auth tab (spec 0069) writes through
    /// this function — it must round-trip the pin and leave everything else
    /// in the file untouched (comments, unrelated tables).
    #[test]
    fn set_smith_model_pin_writes_and_preserves_unrelated_content() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let paths = tmp_paths(tmp.path());
        std::fs::write(
            paths.config_file(),
            "# a comment worth keeping\n[defaults]\nworktree = true\n",
        )
        .expect("write");

        set_smith_model_pin(&paths, Some("claude-oauth:claude-sonnet-4-6")).expect("set pin");
        let written = std::fs::read_to_string(paths.config_file()).expect("read");
        assert!(written.contains("# a comment worth keeping"));
        assert!(written.contains("[defaults]"));
        assert!(written.contains("worktree = true"));
        assert!(written.contains("[adapters.smith.env]"));
        assert!(written.contains(r#"CONSTRUCT_SMITH_MODEL = "claude-oauth:claude-sonnet-4-6""#));

        set_smith_model_pin(&paths, None).expect("clear pin");
        let cleared = std::fs::read_to_string(paths.config_file()).expect("read");
        assert!(!cleared.contains("CONSTRUCT_SMITH_MODEL"));
        assert!(cleared.contains("# a comment worth keeping"));
        assert!(cleared.contains("worktree = true"));
    }

    /// No pre-existing `config.toml` (fresh install): the write creates the
    /// config dir and file rather than erroring.
    #[test]
    fn set_smith_model_pin_creates_file_when_absent() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let paths = tmp_paths(&tmp.path().join("nested"));
        set_smith_model_pin(&paths, Some("ollama:llama3.1")).expect("set pin");
        let written = std::fs::read_to_string(paths.config_file()).expect("read");
        assert!(written.contains(r#"CONSTRUCT_SMITH_MODEL = "ollama:llama3.1""#));
    }

    /// `[adapters.<name>].env` parses out of TOML and lands on the
    /// resolved AdapterConfig.
    #[test]
    fn adapter_env_table_parses() {
        let toml = r#"
            [adapters.smith]
            binary = "construct-adapter-smith"
            env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5", DEBUG = "1" }
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert_eq!(
            smith.env.get("CONSTRUCT_SMITH_MODEL").map(String::as_str),
            Some("codex-oauth:gpt-5.5"),
        );
        assert_eq!(smith.env.get("DEBUG").map(String::as_str), Some("1"));
    }

    /// Omitting `env` is fine — it defaults to empty rather than
    /// failing the parse.
    #[test]
    fn adapter_env_defaults_to_empty() {
        let toml = r#"
            [adapters.smith]
            binary = "construct-adapter-smith"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert!(smith.env.is_empty());
    }

    /// REGRESSION: declaring `[adapters.smith] env = {…}` (to set
    /// per-harness env defaults — the motivating use case for that
    /// field) must NOT drop the built-in `binary` / `description`
    /// values that the daemon needs to actually spawn the adapter.
    ///
    /// Before this fix, the BUILTIN_ADAPTERS layer used
    /// `or_insert_with`, which only fired when the entry was
    /// missing entirely. A user-supplied entry that lacked `binary`
    /// got NO `binary` field, the daemon fell back to looking up a
    /// binary named bare `smith` (not `construct-adapter-smith`),
    /// and session create failed with "adapter binary not found".
    #[test]
    fn user_partial_adapter_config_keeps_builtin_binary() {
        let toml = r#"
            [adapters.smith]
            env = { CONSTRUCT_SMITH_MODEL = "codex-oauth:gpt-5.5" }
        "#;
        let mut cfg: Config = toml::from_str(toml).expect("parse");
        // Mimic Config::load's builtin-layering step (the actual
        // load() walks the filesystem, which we'd rather not in
        // tests).
        for b in BUILTIN_ADAPTERS {
            let entry = cfg.adapters.entry(b.name.to_string()).or_default();
            if entry.binary.is_none() {
                entry.binary = Some(b.binary.to_string());
            }
            if entry.args.is_empty() {
                entry.args = b.args.iter().map(|s| s.to_string()).collect();
            }
            if entry.description.is_none() {
                entry.description = Some(b.description.to_string());
            }
        }
        let smith = cfg.adapters.get("smith").expect("smith adapter");
        assert_eq!(
            smith.binary.as_deref(),
            Some("construct"),
            "user-supplied [adapters.smith] with only `env` set must still pick up the built-in binary path",
        );
        // And the user's env stays in place.
        assert_eq!(
            smith.env.get("CONSTRUCT_SMITH_MODEL").map(String::as_str),
            Some("codex-oauth:gpt-5.5"),
        );
    }

    /// `[program].templates_dir` parses out of TOML.
    #[test]
    fn program_templates_dir_parses() {
        let toml = r#"
            [program]
            templates_dir = "/srv/program-templates"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        assert_eq!(
            cfg.program.templates_dir.as_deref(),
            Some("/srv/program-templates")
        );
    }

    /// Resolution precedence: env override > `[program].templates_dir` > default.
    #[test]
    fn resolve_program_templates_dir_precedence() {
        let mut cfg = Config::default();

        // Default: no env, no config → None (daemon uses data_dir/program/templates).
        assert_eq!(resolve_program_templates_dir(&cfg, None), None);

        // Config only.
        cfg.program.templates_dir = Some("/from/config".to_string());
        assert_eq!(
            resolve_program_templates_dir(&cfg, None),
            Some(PathBuf::from("/from/config")),
        );

        // Env wins over config.
        assert_eq!(
            resolve_program_templates_dir(&cfg, Some("/from/env")),
            Some(PathBuf::from("/from/env")),
        );

        // Blank/whitespace values are ignored (fall through to the next source).
        assert_eq!(
            resolve_program_templates_dir(&cfg, Some("   ")),
            Some(PathBuf::from("/from/config")),
        );
        cfg.program.templates_dir = Some("  ".to_string());
        assert_eq!(resolve_program_templates_dir(&cfg, Some("")), None);
    }

    /// `Config::effective_usage_probe` (spec 0086): absent `usage_probe`
    /// falls back to the harness's built-in default command; a harness with
    /// no built-in default (and no override) has probing disabled.
    #[test]
    fn effective_usage_probe_absent_falls_back_to_builtin_default() {
        let cfg = Config::default();
        assert_eq!(cfg.effective_usage_probe("claude"), Some("/usage"));
        assert_eq!(cfg.effective_usage_probe("codex"), Some("/status"));
        assert_eq!(cfg.effective_usage_probe("agy"), Some("/usage"));
        assert_eq!(cfg.effective_usage_probe("grok"), Some("/usage show"));
        // No built-in default and no override -> disabled.
        assert_eq!(cfg.effective_usage_probe("shell"), None);
        assert_eq!(cfg.effective_usage_probe("smith"), None);
    }

    /// Explicit `usage_probe = ""` disables the probe even though the
    /// harness has a built-in default — TOML has no null literal, so this
    /// is the only way to represent "explicitly off".
    #[test]
    fn effective_usage_probe_empty_string_disables() {
        let toml = r#"
            [adapters.claude]
            usage_probe = ""
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        assert_eq!(cfg.effective_usage_probe("claude"), None);
    }

    /// Any other string overrides the built-in default verbatim.
    #[test]
    fn effective_usage_probe_override_string_wins() {
        let toml = r#"
            [adapters.codex]
            usage_probe = "/status --verbose"
        "#;
        let cfg: Config = toml::from_str(toml).expect("parse");
        assert_eq!(
            cfg.effective_usage_probe("codex"),
            Some("/status --verbose")
        );
    }
}
